{% set version = '2.3-51' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-chron
  version: {{ version|replace("-", "_") }}

source:
  fn: chron_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/chron_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/chron/chron_{{ version }}.tar.gz
  sha256: 881745b713f93f000aea323fcd04d77c62e920de4b5ac9171c9bdbc45fb45f15


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: scales, ggplot2
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('chron')"           # [not win]
    - "\"%R%\" -e \"library('chron')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=chron
  license: GPL-2
  summary: Provides chronological objects which can handle dates and times.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: chron
# Version: 2.3-51
# Title: Chronological Objects which can Handle Dates and Times
# Description: Provides chronological objects which can handle dates and times.
# Authors@R: c(person("David", "James", role = "aut", comment = "S original"), person("Kurt", "Hornik", role = c("aut", "trl", "cre"), email = "Kurt.Hornik@R-project.org"), person("Gabor", "Grothendieck", role = "ctb", email = "ggrothendieck@gmail.com"))
# Depends: R (>= 2.12.0)
# Imports: graphics, stats
# Suggests: scales, ggplot2
# Enhances: zoo
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2017-10-07 12:34:48 UTC; hornik
# Author: David James [aut] (S original), Kurt Hornik [aut, trl, cre], Gabor Grothendieck [ctb]
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-10-07 16:09:51 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
