travis:
  secure:
    BINSTAR_TOKEN: XORlaOl+7Neczjf5hCx7wsxnfg32DDW4QGrBri+XjbjuLtMekXZyr+SPu+g+5AmddZpVsbZUoxZypbXeVxgZZkegfH1FZQEK7rrC+MVkiY3Mhypdsco0QlYig6gk/sd/RDjXoonnaDrI4sbhdcgMdKttdcP8jNyXpL/zRembdXHkX0QUSLCkUlDGvjh6IDQW29+09ZBwvr0RX8faVtxlhtT5fCGpQwveUIsLJ4blklkZgV5wL8WTlXUx4Ew/wj2GsoWoj7lI5CantNti2OrQQ66po1pbxVHxoTA1zZwbuOep6odkrx0ixlSmPLbVDAprSXccm1Doh3vtaS4W57Q5VuCK/Qr2WY/BUVmfSXnKmcIMrp+u4w6fV7vfm8GMOIr//H1PDhvWxJJwjKL22OUMA949RevYSJNBtzPl0fOo2bKwSStndQCJoYXBw47pNw75qFpaKjmPrXWjlLR9EU2f2AqbVr5pYzQeWZxJMqkcooyw+05AkE/JVFdM+mlN1y2G8xnjFgD4HUqt7AxeJ/KWLlJDmt5L5qdprc7bNfGGgi+RgZYhd1TsL7QRBUnF9HI7ykGpwxAxPxc+U7WksK0FIg3NR08ozs0EVYQhsbZEhHJ0UrgiverjB9u3yRR8tpvYhUQS6MDh4lgbk4OtONZxtM5Qx8Y+aXXErEVecv4KdGE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
