travis:
  secure:
    BINSTAR_TOKEN: mPS5GEtfdqvOe6oZ7bYTMf/ZdMdH7jPeEvVhNe8fJd1ZEyXr3LO5QbuRdKS9NKgWJqkKBq9mPGE/7vGstZUgZto2LsBqGKwwPiH/qvhC+4K6xF1zDZlQ+iafJKLwgRWAHLA4W10pB0BwCMlu7sFLYML4/wgpLRYw2qNDEajvYJirPHJ9fuboZNqhREgQO9I0PEwi3mkT7epXSWvi9OxrIX4iM3Di8pTuPkIZnMz8GVY2Zm6MprqKrC4Y+o1s1UCaHTvgUtFZQulEHRPvFz+PVwFkcCv5cXM6GTOh0G42R9PA8524y093fFA0zeSsvKGZT4Vzr9bp3eldqQWWVpzgGVqgoIsMhCsXXB0TkYh8tr3KEVdVYHlufR/+OUka5glbj0+eeP6tGRc/DFNeULjLQviEoMl19BpRrTrWLehOZiDtqKoj0kBGfy2oBIMTsKB6dCketNmTm7TdEY0/Ymn0ePYfhcwUOP+4chtFhdEJOtkm1Ou//69/NeyUhsrJ6rqVP3q3JoH74ck27bNEQEeNEkifNsrTzc+xtqvOjzp3jMvmgldjU5vs/+mXEI+ePoNdYFj4ejHWxVnXuC2g3qK12crlrO19yFcVdlimuGVgSTNxurCG5FuqgOw95ag2Mn3Hr6l9hJWgkeBl6f/fXcL9dTrWpCMSxh0qX1Leeb5eJgM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
